
version: '3.1'
services:
  theia:
    container_name: theia-python
    build: 
      context:
        ./docker
      dockerfile: dockerfile
    ports: 
      - 3000:3000
    # dev volume
    # volumes:
      # - ./src:/home/theia
    
    #prod volume
    volumes:
      - ./workspace:/home/project
